/*
 *  b0rk - The b0rk Embeddable Runtime Environment
 *  Copyright (C) 2015, 2016 GeekProjects.com
 *
 *  This file is part of b0rk.
 *
 *  b0rk is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  b0rk is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with b0rk.  If not, see <http://www.gnu.org/licenses/>.
 */

import system.io.File;
/*
 * Simple String allocation and addition test
 */
class tests.Expressions extends system.lang.Test
{
    function main() static
    {
        var a = 2;
        var b = 3;

        assertEquals("- ", a - b, -1);
        assertEquals("+ ", a + b, 5);
        assertEquals("* ", a * b, 6);
        assertEquals("/ ", 6 / b, 2);

        assertEquals("< ", a < b, true);
        assertEquals("<=", a <= b, true);
        assertEquals("> ", a > b, false);
        assertEquals(">=", a >= b, false);
        assertEquals("==", a == b, false);
        assertEquals("!=", a != b, true);

        assertEquals("!true", !true, false);
        assertEquals("!false", !false, true);

        assertEquals("Precedence 1", (1 + a * b), 7);
        assertEquals("Precedence 2", (a * b + 1), 7);
        assertEquals("Precedence 3", ((1 + a) * b), 9);
        assertEquals("Precedence 4", (a * (b + 1)), 8);
        assertEquals("Precedence 5", (a * b + 1 * a), 8);

        var i = 1;
        assertEquals("Increment", i++, 1);
        assertEquals("Decrement", i--, 2);
        assertEquals("Decrement(After)", i, 1);

        i += 1;
        assertEquals("Add/Assign", i, 2);
        i -= 1;
        assertEquals("Sub/Assign", i, 1);
    }
}

