/*
 *  b0rk - The b0rk Embeddable Runtime Environment
 *  Copyright (C) 2015, 2016 GeekProjects.com
 *
 *  This file is part of b0rk.
 *
 *  b0rk is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  b0rk is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with b0rk.  If not, see <http://www.gnu.org/licenses/>.
 */

import system.io.File;
/*
 * Simple String allocation and addition test
 */
class tests.Expressions
{

    function test(name, t, expected) static
    {
        File.out.write("Expression: " + name);
        File.out.write(": ");
        if (t == expected)
        {
            File.out.writeln("PASS");
        }
        else
        {
            File.out.write("FAIL: expected=" + expected);
            File.out.writeln(" got=" + t);
        }
    }

    function main() static
    {
        var a = 2;
        var b = 3;

        test("- ", a - b, -1);
        test("+ ", a + b, 5);
        test("* ", a * b, 6);
        test("/ ", 6 / b, 2);

        test("< ", a < b, true);
        test("<=", a <= b, true);
        test("> ", a > b, false);
        test(">=", a >= b, false);
        test("==", a == b, false);
        test("!=", a != b, true);

        test("!true", !true, false);
        test("!false", !false, true);

        test("Precedence 1", (1 + a * b), 7);
        test("Precedence 2", (a * b + 1), 7);
        test("Precedence 3", ((1 + a) * b), 9);
        test("Precedence 4", (a * (b + 1)), 8);
        test("Precedence 5", (a * b + 1 * a), 8);

        var i = 1;
        test("Increment", i++, 1);
        test("Decrement", i--, 2);
        test("Decrement(After)", i, 1);

        i += 1;
        test("Add/Assign", i, 2);
        i -= 1;
        test("Sub/Assign", i, 1);
    }
}

