/*
 *  b0rk - The b0rk Embeddable Runtime Environment
 *  Copyright (C) 2015, 2016 GeekProjects.com
 *
 *  This file is part of b0rk.
 *
 *  b0rk is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  b0rk is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with b0rk.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * 
 */
class tests.Functions
{
    var func;
    var id;
    function Functions(idParam)
    {
        id = idParam;
        func = function(param)
        {
            system.io.File.out.writeln("Hello from Function! param=" + param);
            system.io.File.out.writeln("Hello from Function! param.id=" + param.id);
param.id = 123;
        };
    }

    function main() static
    {
        var func;
        func = function()
        {
            system.io.File.out.writeln("Hello from func!");
        };
        var i;
        for (i = 0; i < 10; i++)
        {
            func();
        }

        var funcObj = new tests.Functions("1");
        funcObj.func(funcObj);
        new tests.Functions("2").func(funcObj);
    }
}

