
language: cpp
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8

before_install:
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

before_script:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install libpng libxml2 jpeg; fi
  - bash ./build/travis.sh
  - ./autogen.sh --verbose 
  - ./configure

script: make && make test

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

