
language: cpp
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - libsigc++-2.0-dev
      - sqlite3
      - libsqlite-dev
  homebrew:
    packages:
      - libsigc++
      - libtool
    #update: true

before_script:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install libpng libxml2 jpeg; fi
  - bash ./build/travis.sh
  - ./autogen.sh --verbose 
  - ./configure

script: make && make test

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

