/*
 *  b0rk - The b0rk Embeddable Runtime Environment
 *  Copyright (C) 2015, 2016 GeekProjects.com
 *
 *  This file is part of b0rk.
 *
 *  b0rk is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  b0rk is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with b0rk.  If not, see <http://www.gnu.org/licenses/>.
 */

import system.io.File;

/*
 * Allocates lots of objects and doesn't do much with them
 * This should cause the Garbage Collector to do a lot of
 * work clearing up!
 */
class tests.GCStress
{
    var field1;
    function GCTest()
    {
        field1 = new String("Hello");
        new String("World");
    }

    function main() static
    {
        var i;
        File.out.writeln("Creating lots of objects...");
        for (i = 0; i < 10000000; i++)
        {
            var obj;
            obj = new tests.GCStress();
        }
        File.out.writeln("Done!");
    }
}

