import system.io.File;
/*
 * Simple String allocation and addition test
 */
class tests.If
{
    function main() static
    {
        var a = 2;
        var b = 3;
        if (a == b)
        {
            File.out.writeln("it doesn't work :(");
        }
        else if (a < b)
        {
            File.out.writeln("it works!");
        }
        else if (a == 12345)
        {
            File.out.writeln("it doesn't work :(");
        }
        else
        {
            File.out.writeln("it doesn't work :(");
        }
        File.out.writeln("Done!");
    }
}

