
class Mandelbrot
{
    function main() static
    {
        var maxIteration = 40;
        System.log("P2");
        System.log("400 400");
        System.log(maxIteration);
        var py;
        for (py = -2.0; py < 2.0; py += 0.01)
        {
            var px;
            for (px = -2.0; px < 2.0; px += 0.01)
            {
                var x = 0.0;
                var y = 0.0;
                var iteration = 0;
                while ((((x * x) + (y * y)) < (2 * 2)) && iteration < maxIteration)
                {
                    var xtemp = ((x * x) - (y * y)) + px;
                    y = (2 * x * y) + py;
                    x = xtemp;
                    iteration++;
                }
                System.log(iteration);
            }
        }
    }
}

