
import system.io.File;
import system.lang.Maths;

class tests.Mandelbrot
{
    var maxIterations;

    function Mandelbrot()
    {
        maxIterations = 20;
    }

    function iterate(px, py)
    {
        var x = 0.0;
        var y = 0.0;
        var iteration = 0;
        while ((((x * x) + (y * y)) < (2.0 * 2.0)) && iteration < maxIterations)
        {
            var xtemp = ((x * x) - (y * y)) + px;
            y = (2.0 * x * y) + py;
            x = xtemp;
            iteration++;
        }
        return iteration;
    }

    function generate()
    {
        var minX = -2.0;
        var minY = -2.0;
        var maxX = 2.0;
        var maxY = 2.0;
        var step = 0.005;
        //var step = 0.01;

        var width = (maxX - minX) / step;
        var height = (maxY - minY) / step;

        File.out.writeln("P2");
        File.out.write(Maths.round(width));
        File.out.write(" ");
        File.out.writeln(Maths.round(height));
        File.out.writeln(maxIterations);
        var py;
        for (py = minY; py < maxY; py += step)
        {
            var px;
            for (px = minX; px < maxX; px += step)
            {
                File.out.writeln(iterate(px, py));
            }
        }
    }

    function main() static
    {
        var mandelbrot = new tests.Mandelbrot();
        mandelbrot.generate();
    }
}

