
import system.io.File;

class tests.Mandelbrot
{
    var maxIterations;

    function Mandelbrot()
    {
        maxIterations = 20;
    }

    function iterate(px, py)
    {
        var x = 0.0;
        var y = 0.0;
        var iteration = 0;
        while ((((x * x) + (y * y)) < (2.0 * 2.0)) && iteration < maxIterations)
        {
            var xtemp = ((x * x) - (y * y)) + px;
            y = (2.0 * x * y) + py;
            x = xtemp;
            iteration++;
        }
        return iteration;
    }

    function generate()
    {
        File.out.write("P2");
        File.out.write("400 400");
        File.out.write(maxIterations);
        var py;
        for (py = -2.0; py < 2.0; py += 0.01)
        {
            var px;
            for (px = -2.0; px < 2.0; px += 0.01)
            {
                File.out.write(iterate(px, py));
            }
        }
    }

    function main() static
    {
        var mandelbrot = new tests.Mandelbrot();
        mandelbrot.generate();
    }
}

