/*
 *  b0rk - The b0rk Embeddable Runtime Environment
 *  Copyright (C) 2015, 2016 GeekProjects.com
 *
 *  This file is part of b0rk.
 *
 *  b0rk is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  b0rk is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with b0rk.  If not, see <http://www.gnu.org/licenses/>.
 */


class BaseClass
{
    var m_id;
    function BaseClass()
    {
        system.io.File.write("BaseClass: Here!");
        m_id = 1234;
    }

    function printId()
    {
        system.io.File.write("BaseClass.printId: m_id=" + m_id);
    }
}

class NewTest extends BaseClass
{
    var m_data;

    function NewTest(data, id)
    {
m_id = id;
        m_data = data;
        system.io.File.write("NewTest: id=" + id);
        system.io.File.write("NewTest: data=" + data);
        system.io.File.write("NewTest: m_id=" + m_id);
        system.io.File.write("NewTest: m_data=" + m_data);
    }

    function print()
    {
        system.io.File.write("NewTest.print: m_data=" + m_data);
        system.io.File.write("NewTest.print: m_id=" + m_id);
    }

    function main() static
    {
        var obj1 = new NewTest("Hello", 12345);
        var obj2 = new NewTest("World", 54321);
        obj1.print();
        obj1.printId();
        obj2.print();
        obj2.printId();
        new NewTest("And Another", 1337).print();
    }
}

