
class NewTest
{
    var m_data;

    function NewTest(data)
    {
        m_data = data;
        System.log("NewTest: m_data=" + m_data);
    }

    function print()
    {
        System.log("NewTest.print: m_data=" + m_data);
    }

    function main() static
    {
        var obj1 = new NewTest("Hello");
        var obj2 = new NewTest("World");
        obj1.print();
        obj2.print();
    }
}

