/*
 * Simple String allocation and addition test
 */
class tests.Strings
{
    function main() static
    {
        var str = "hello";
        str += " world";
        str += new system.lang.String("!");
        system.io.File.out.writeln("result: " + str);
        system.io.File.out.writeln("length: " + str.length());

        var i;
        for (i = 0; i < str.length(); i++)
        {
            system.io.File.out.writeln(("char " + i) + " = " + str.at(i));
        }
    }
}

