/*
 *  b0rk - The b0rk Embeddable Runtime Environment
 *  Copyright (C) 2015, 2016 GeekProjects.com
 *
 *  This file is part of b0rk.
 *
 *  b0rk is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  b0rk is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with b0rk.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Simple String allocation and addition test
 */
class tests.UTF8
{
    function ☺() static
    {
        var i;
        for (i = 0; i < 10; i++)
        {
            system.io.File.out.write("☺");
        }
        system.io.File.out.writeln("");
    }

    function main() static
    {
        ☺();

        // Russian - 56 characters
        var utf8_1="В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!";
        system.io.File.out.writeln("UTF8 1: length: " + utf8_1.length());
        system.io.File.out.writeln("UTF8 1: " + utf8_1);

        var i;
        for (i = 0; i < utf8_1.length(); i++)
        {
            system.io.File.out.writeln(("char " + i) + " = " + utf8_1.at(i));
        }
    }
}

