
class VarTest
{
    function main() static
    {
        var i; 
        for (i = 0; i < 2; i++)
        {
            var j; 
            for (j = 0; j < 2; j++)
            {
                var k; 
                for (k = 0; k < 3; k++)
                {
                    system.io.File.write("i=" + new system.lang.String(i) + ", j=" + new system.lang.String(j) + ", k=" + new system.lang.String(k));
                }
            }
        }
    }
}

